/** Design: Ledger of Justice — a focused, click-to-expand rule sheet that explains residual heir order without hiding review boundaries. */
import { useState } from "react";
import { BookOpenCheck, ChevronDown, Scale } from "lucide-react";
import type { AppLanguage } from "@/lib/inheritance";

type AsabaGuideProps = { language?: AppLanguage };

const copy = {
  ta: {
    button: "மீதிப் பங்கு வரிசையைப் பார்க்கவும்", title: "அஸபா — மீதிப் பங்கு பெறும் வரிசை", intro: "கட்டாயப் பங்குகள் கொடுத்த பின், மீதமுள்ள தொகை கீழே உள்ள முன்னுரிமை வரிசைப்படி செல்கிறது.", self: "1. தானாக மீதிப் பங்கு", through: "2. ஆண் உடன் மீதிப் பங்கு", with: "3. பெண் வாரிசுடன் மீதிப் பங்கு", degrees: ["முதல்: மகன் → மகனின் மகன் → கீழ் ஆண் சந்ததி", "இரண்டாம்: அப்பா → அப்பாவின் அப்பா → மேல் ஆண் மூதாதையர்", "மூன்றாம்: உடன்பிறந்த சகோதரர் → தந்தை வழி சகோதரர் → அவர்களின் மகன்கள்", "நான்காம்: முழு தந்தை வழி மாமா (அம்) → தந்தை வழி பாதி மாமா → அவர்களின் மகன்கள்"], throughRules: ["மகன் + மகள்: மகனுக்கு 2, மகளுக்கு 1", "மகனின் மகன் + மகனின் மகள்: 2:1", "உடன்பிறந்த சகோதரர் + சகோதரி: 2:1", "தந்தை வழி சகோதரர் + சகோதரி: 2:1 — பிள்ளை, தந்தை, தாத்தா, உடன்பிறந்தோர் இல்லாதபோது"], withRules: ["மகள் அல்லது மகனின் மகள் இருக்கும்போது உடன்பிறந்த சகோதரி மீதியைப் பெறலாம்.", "மகள் அல்லது மகனின் மகள் இருக்கும்போது தந்தை வழி சகோதரி மீதியைப் பெறலாம்."], examplesTitle: "எளிய உதாரணங்கள்", examples: [["1 மகன் + 1 மகள்", "மீதித் தொகை 2:1 — மகன் 2 பங்கு, மகள் 1 பங்கு."], ["3 மகள்கள்; மகன் இல்லை", "மகள்களின் நிர்ணயப் பங்கு மொத்தம் 2/3; மூவரும் சமமாகப் பகிர்வர். மற்ற வாரிசுகள் அல்லது மீதிப் பகிர்வு இருந்தால் இறுதி தொகை மாறலாம்."], ["3 ஒரே நிலை ஆண் வாரிசுகள்", "3 மகன்கள் அல்லது 3 தகுதியுள்ள உடன்பிறந்த சகோதரர்கள்: மீதியை சமமாகப் பகிர்வர்."]], automatic: "தானியங்கி", review: "அறிஞர் மறுஆய்வு" },
  en: {
    button: "See the residuary-heir order", title: "‘Asaba — order for the remaining estate", intro: "After fixed shares, the remaining estate follows this priority order.", self: "1. Residuary by self", through: "2. Residuary through another", with: "3. Residuary with another", degrees: ["First: son → son’s son → lower male descendants", "Second: father → paternal grandfather → higher male ascendants", "Third: full brother → paternal half-brother → their sons", "Fourth: full paternal uncle (ʿamm) → consanguine paternal uncle → their sons"], throughRules: ["Son + daughter: son takes 2 parts; daughter takes 1", "Son’s son + son’s daughter: 2:1", "Full brother + full sister: 2:1", "Paternal brother + paternal sister: 2:1 when no descendant, father, grandfather, or full sibling is present"], withRules: ["A full sister can take the remainder with a daughter or son’s daughter.", "A paternal sister can take the remainder with a daughter or son’s daughter."], examplesTitle: "Simple examples", examples: [["One son + one daughter", "The remainder is split 2:1 — the son receives 2 parts and the daughter receives 1 part."], ["Three daughters; no son", "Their fixed Qur’anic share is 2/3 collectively, divided equally. Other heirs or any applicable redistribution can change the final total."], ["Three same-rank male heirs", "Three sons, or three eligible full brothers, divide the remainder equally."]], automatic: "Automatic where supported", review: "Scholar review when needed" },
  ar: {
    button: "عرض ترتيب العصبة", title: "العصبة — ترتيب الباقي من التركة", intro: "بعد الأنصبة المفروضة، يتبع الباقي ترتيب الأولوية الآتي.", self: "1. العصبة بالنفس", through: "2. العصبة بالغير", with: "3. العصبة مع الغير", degrees: ["الأولى: الابن ← ابن الابن ← الذرية الذكورية الأدنى", "الثانية: الأب ← جد الأب ← الأصول الذكور الأعلى", "الثالثة: الأخ الشقيق ← الأخ لأب ← أبناؤهما", "الرابعة: العم الشقيق (عم) ← العم لأب ← أبناؤهما"], throughRules: ["ابن + بنت: للابن سهمان وللبنت سهم", "ابن الابن + بنت الابن: 2:1", "أخ شقيق + أخت شقيقة: 2:1", "أخ لأب + أخت لأب: 2:1 عند عدم وجود فرع وارث أو أب أو جد أو أخ شقيق"], withRules: ["قد تأخذ الأخت الشقيقة الباقي مع البنت أو بنت الابن.", "قد تأخذ الأخت لأب الباقي مع البنت أو بنت الابن."], examplesTitle: "أمثلة بسيطة", examples: [["ابن واحد + بنت واحدة", "يقسم الباقي 2:1: للابن سهمان وللبنت سهم."], ["ثلاث بنات، ولا ابن", "نصيبهن المفروض 2/3 مجتمعاً ويوزع بالتساوي. قد يتغير الإجمالي النهائي بوجود ورثة آخرين أو رد مناسب."], ["ثلاثة ورثة ذكور في الرتبة نفسها", "ثلاثة أبناء، أو ثلاثة إخوة أشقاء مؤهلين، يقتسمون الباقي بالتساوي."]], automatic: "تلقائي عند دعم القاعدة", review: "مراجعة مختص عند الحاجة" },
} as const;

export function AsabaGuide({ language = "ta" }: AsabaGuideProps) {
  const [open, setOpen] = useState(false);
  const text = copy[language];
  return <section className="border border-blue-100 bg-white"><button type="button" onClick={() => setOpen((value) => !value)} className="flex min-h-14 w-full items-center justify-between gap-3 px-4 text-start hover:bg-blue-50"><span className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-full bg-[#133D76] text-white"><Scale size={16} /></span><span><span className="block text-sm font-extrabold text-[#133D76]">{text.button}</span><span className="mt-0.5 block text-[11px] text-slate-500">{text.automatic} · {text.review}</span></span></span><ChevronDown size={18} className={`shrink-0 text-[#133D76] transition ${open ? "rotate-180" : ""}`} /></button>{open ? <div className="border-t border-blue-100 px-4 pb-5 pt-4"><div className="flex items-start gap-3 border-s-2 border-[#B8892D] bg-amber-50/60 p-3"><BookOpenCheck size={17} className="mt-0.5 shrink-0 text-[#B8892D]" /><div><h3 className="font-extrabold text-slate-950">{text.title}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{text.intro}</p></div></div><div className="mt-4 grid gap-4 lg:grid-cols-3"><section><h4 className="text-sm font-extrabold text-[#133D76]">{text.self}</h4><ol className="mt-2 space-y-2">{text.degrees.map((item, index) => <li key={item} className="flex gap-2 text-xs leading-5 text-slate-600"><span className="font-bold text-[#B8892D]">{index + 1}.</span>{item}</li>)}</ol></section><section><h4 className="text-sm font-extrabold text-[#133D76]">{text.through}</h4><ul className="mt-2 space-y-2">{text.throughRules.map((item) => <li key={item} className="text-xs leading-5 text-slate-600">• {item}</li>)}</ul></section><section><h4 className="text-sm font-extrabold text-[#133D76]">{text.with}</h4><ul className="mt-2 space-y-2">{text.withRules.map((item) => <li key={item} className="text-xs leading-5 text-slate-600">• {item}</li>)}</ul></section></div><div className="mt-5 border-t border-slate-100 pt-4"><p className="text-sm font-extrabold text-[#133D76]">{text.examplesTitle}</p><div className="mt-2 grid gap-2 md:grid-cols-3">{text.examples.map(([title, detail]) => <article key={title} className="border border-slate-200 bg-slate-50 p-3"><p className="text-sm font-extrabold text-slate-900">{title}</p><p className="mt-1 text-xs leading-5 text-slate-600">{detail}</p></article>)}</div></div></div> : null}</section>;
}
